twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    date:
        format: 'M d, Y g:i A'
        timezone: 'Europe/Dublin'
when@test:
    twig:
        strict_variables: true
